FROM rocketbuddha/ww-sp-java17-builder:0.10 AS builder
WORKDIR /tmp/ww/mlqs-amqp-ingester
COPY . .
RUN mvn clean package -DskipTests
FROM openjdk:17-jdk-slim
WORKDIR /opt/ww/mlqs-amqp-ingester
COPY --from=builder /tmp/ww/mlqs-amqp-ingester/target/mlqs-amqp-ingester.jar /opt/ww/mlqs-amqp-ingester
CMD ["java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", "-jar", "mlqs-amqp-ingester.jar", "--spring.profiles.active=compose"]